### ISSUE TITLE
Need reduce the dialog

### ISSUE THREAD

**Issue by invizorys** [mukeshsolanki/country-picker-android#2]
Need to reduce the dialog when the keyboard is open because some countries have overlapping by keyboard.

P.S. Where is located a code of library?

**Comment by mukeshsolanki** [comment]
The CountryPicker extends the DialogFragment allowing you to modify it as needed. You could choose how you want the dialog to change size as you desire.

The country code or the country details are located in an encoded string inside the file called country_codes.xml under values.
