### ISSUE TITLE
Dialog doesn't close and select a country

### ISSUE THREAD

**Issue by bashan** [mukeshsolanki/country-picker-android#28]
I am using exactly the same code in the example.
The dialog shows properly, but when clicking a country for selection the dialog doesn't close and the event: "onSelectCountry" is not fired.

**Comment by mukeshsolanki** [comment]
Have you set the listener?

**Comment by mukeshsolanki** [comment]
no response

**Comment by Francagir** [comment]
I have a similar problem, the country is set but then the dialog does not close,
