### ISSUE TITLE
Keyboard down

### ISSUE THREAD

**Issue by annalaufey** [mukeshsolanki/country-picker-android#29]
Hi, how can I prevent the keyboard from popping up when I open the dialog?

**Comment by mukeshsolanki** [comment]
I'm not sure what you mean by this? The keyboard not supposed to be doing that? can you please explain what you're doing here? maybe a code sample.

**Comment by mukeshsolanki** [comment]
No response closing issue

**Comment by Transformat** [comment]
Hi, When we open the dialog and then select the country, they keyboard stays there and is not hidden.

**Comment by Transformat** [comment]
Update this method in CountryPickerDialog class :- 
    @Override
    public void onItemClicked(Country country) {
        if (listener != null) {
            listener.onSelectCountry(country);
        }
        InputMethodManager imm = (InputMethodManager) getContext().getSystemService(
                Context.INPUT_METHOD_SERVICE);
        imm.hideSoftInputFromWindow(searchEditText.getWindowToken(), 0);
        dismiss();
    }
