### ISSUE TITLE
Need to show only few countries

### ISSUE THREAD

**Issue by didiosn** [mukeshsolanki/country-picker-android#32]
Hi, Good job on this library.

Is that a way to limit the list ? 
I want to let the user pick between only , maybe, 10 countries that i'v choosen.
(sorry for bad english)

**Comment by mukeshsolanki** [comment]
you can use the method `setCountriesList` to set only the countries you want to display

**Comment by Tindi** [comment]
Hi, Just stumbled on this and I think its really dope. Sorry for reopening this thread but how do set my own countries? I've seen this:

`countryPicker.setCountries(List<Country> countries);`

Do I create a new Country object? Kindly clarify this for me. Thanks
