### ISSUE TITLE
Sorting countries by name

### ISSUE THREAD

**Issue by robalcnj** [mukeshsolanki/country-picker-android#33]
The list is not sorted by the country name, is there a option or a feature that can do this, or do I need to sort it my self?

**Comment by srikanthkancheti** [comment]
Following code will solve your problem 👍 

    final CountryPicker picker = CountryPicker.newInstance("Select Country");  // dialog title
        List<Country> countryArrayList = new ArrayList<>();
        countryArrayList = Country.getAllCountries();
        Collections.sort(countryArrayList, new Comparator<Country>() {
            @Override
            public int compare(Country country1, Country country2) {
                return country1.getName().trim().compareToIgnoreCase(country2.getName().trim());
            }
        });
        picker.setCountriesList(countryArrayList);

**Comment by robalcnj** [comment]
thank you for the code snipped, I have already solved this in a similar way, but I was wondering if there's a convenient internal method to be called.

**Comment by mukeshsolanki** [comment]
This can now be done with the library

**Comment by visionfaysal** [comment]
**Use this code You can add only selected Countries In your app**

```
final CountryPicker picker = CountryPicker.newInstance("Select Country");
        List<Country> countryArrayList = new ArrayList<>();
        countryArrayList.add(new Country("AU", "Australia", "+61", com.ybs.countrypicker.R.drawable.flag_au));
        countryArrayList.add( new Country("GB", "United Kingdom", "+44", com.ybs.countrypicker.R.drawable.flag_gb));
        picker.setCountriesList(countryArrayList);
```

**Comment by visionfaysal** [comment]
**How i can set Default Country On picker ????**
