### ISSUE TITLE
Country "Sint Maarten" has a empty space character in front of the name

### ISSUE THREAD

**Issue by robalcnj** [mukeshsolanki/country-picker-android#34]
The string in the country list for the country "Sint Maarten" is " Sint Maarten" and it does not sort as it should because of that

**Comment by srikanthkancheti** [comment]
I also got the same problem, here is the solution. We have to trim the name while sorting

    List<Country> countryArrayList = new ArrayList<>();
        countryArrayList = Country.getAllCountries();
        Collections.sort(countryArrayList, new Comparator<Country>() {
            @Override
            public int compare(Country country1, Country country2) {
                return country1.getName().trim().compareToIgnoreCase(country2.getName().trim());
            }
        });

**Comment by mukeshsolanki** [comment]
Fixed in v`1.2.1`
