### ISSUE TITLE
can add one item more

### ISSUE THREAD

**Issue by hvar90** [mukeshsolanki/country-picker-android#37]
is necessary can add more items to the list, for example i need add an item where this one is ALL COUNTRIES so when the user select this item i know he wants to filter all countries 
because  i am creating a filter with this library 
this would be like your method setCountriesList() but instead put setCountry()
could you please add that ? :)

**Comment by mukeshsolanki** [comment]
sorry that's not a possibility as this is a custom requirement and would not be used by a lot of people. The purpose of the library is to be more generic
