### ISSUE TITLE
How to find latest version for dependency

### ISSUE THREAD

**Issue by tahafarooqui** [mukeshsolanki/country-picker-android#38]
How to find latest version for dependency

**Comment by ciamine** [comment]
compile 'com.github.xingstarx:country-picker-android:1.1.8'

**Comment by mukeshsolanki** [comment]
the latest version can always be seen at the top of the readme.md
![screen shot 2018-03-26 at 11 31 58 am](https://user-images.githubusercontent.com/10584200/37889318-51b4a2da-30e9-11e8-9cff-e735ad71dff1.png)
