### ISSUE TITLE
Crashing on Show in Xamarin Android

### ISSUE THREAD

**Issue by AbhishekSinghThakur** [mukeshsolanki/country-picker-android#44]
File res/mipmap-xxhdpi-v4/icon.png from xml type layout resource ID #0x7f030000
its giving run time exception like this

**Comment by mukeshsolanki** [comment]
@AbhishekSinghThakur can you provide a little more detail please.

**Comment by mukeshsolanki** [comment]
the lib does not use `res/mipmap-xxhdpi-v4/icon.png` can you make sure its not being used by your project. Also can you share the error logs

**Comment by AbhishekSinghThakur** [comment]
I'm also not getting why is giving that kind of errors when I removed the mipmap the error changes but still its crashing.
So why don't you do a favour , make a sample to open country code picker dialog on button click with your nuget in Xamarin android to identify that you lib don't have any issues

**Comment by mukeshsolanki** [comment]
Too much effort to prove the issue is not in the library. your comment `I'm also not getting why is giving that kind of errors when I removed the mipmap the error changes but still its crashing.` above states clearly not an issue with the library

**Comment by AbhishekSinghThakur** [comment]
Bro, I just want to use you lib tell me what I can do in xamarin android simple.
I'm not saying the problem is with lib or something else thing is that Dialog is not appearing in xamarin android and its crashing. Rather then just giving explanation to prove the lib don't have any issue just try it at your end in Xamarin android as I have used same lib in fresh project too and still the same issue its crashing.
