### ISSUE TITLE
Crashing application on Show in Xamarin Android 

### ISSUE THREAD

**Issue by AbhishekSinghThakur** [mukeshsolanki/country-picker-android#45]
Below are the steps I followed in my Xamarin Android project.

I have added the nuget package "Karamunting.Android.MukeshSolanki.CountryPickerAndroid" version="1.1.9" in my project.
Now I just want to display the country code picker dialog so I followed the following Csharp code
CountryPicker countryPicker = new CountryPicker();
countryPicker.Show(this.Activity.SupportFragmentManager, "COUNTRY_PICKER");
countryPicker.CountrySelect += (o, e) => {
// Perform action on click
};

App crashed on show

**Comment by mukeshsolanki** [comment]
duplicate #44

**Comment by mukeshsolanki** [comment]
Update to the latest version and try

**Comment by AbhishekSinghThakur** [comment]
There is only one version available in Visual studio 2017  version="1.1.9"

**Comment by mukeshsolanki** [comment]
@AbhishekSinghThakur can't help you with a deprecated version as there have been 3 version updates after that which fixes a lot of issues
