### ISSUE TITLE
Country constructor is not public

### ISSUE THREAD

**Issue by orcchg** [mukeshsolanki/country-picker-android#47]
How is it supposed to create my own Country (as described in README, to set custom list of countries, load country flag by iso, etc), if all constructors of Country class are package-access ?!

We need to open them and make convenient to use. We need Country.Builder() with setters and default value. Say, i need to show picker for provinces - i'd like to use CountryPicker, but with my own custom list of "countries" (provinces) without flags - just with names and some province codes. I'm not able to do that atm.

**Comment by mukeshsolanki** [comment]
You cannot make your own country.  that somehow does not make much sense to create your own country. If you want to show a custom list of countries then you can simply fetch all the countries with `getAllCountries()` and then simply filter out the ones you want to display

**Comment by orcchg** [comment]
I dont agree. I've described the use case above. First - your constructors are not convenient, it requires all 5 params, but how could we get flag while constructing the Country object?

Second - can't reuse your CountryPicker for, say, list of provinces. Not universal at all. And the reason is just non-public constructors...

**Comment by orcchg** [comment]
Fetch countries and then filter also is O(logN) complexity, rather than having O(1) complexity by setting predefined list of countries.
