### ISSUE TITLE
method can not resolve

### ISSUE THREAD

**Issue by NirmalPrajapat** [mukeshsolanki/country-picker-android#50]
I'm trying to get country name in onCreate( ) method of activity and using getCountryFromSIM( ) method of CountryPicker to get the current country name of the user but its not resolving this method and showing "Cannot resolve method 'getCountryFromSIM(this)' .

**Comment by mukeshsolanki** [comment]
can you try
```  Country countryPicker =
        new CountryPicker.Builder().with(this).listener(new OnCountryPickerListener() {
          @Override public void onSelectCountry(Country country) {
          }
        }).build().getCountryFromSIM(this);
    Log.d("name", countryPicker.getName());```
Note make sure you have a sim in the device if you dont have a sim in the device it will result in NullPointerException

**Comment by NirmalPrajapat** [comment]
![image](https://user-images.githubusercontent.com/14129765/39171795-7db10eec-47bd-11e8-9698-312e6d5534c2.png)

**Comment by NirmalPrajapat** [comment]
what is the latest version of the dependency??

**Comment by mukeshsolanki** [comment]
I think you are using an older version of the library please use the latest version

**Comment by NirmalPrajapat** [comment]
That's okey but in this image method getCountryFromSIM( ) is not from CountryPicker, it is the method of Country class.

![image](https://user-images.githubusercontent.com/14129765/39179915-30036cba-47d3-11e8-8293-0c06a7cd42d9.png)

**Comment by mukeshsolanki** [comment]
no `getCountryFromSim()` belongs to `CountryPicker` class and not `Country` it returns a country.
