### ISSUE TITLE
Country picker dialog width needs to be match_parent

### ISSUE THREAD

**Issue by vamsiandroid** [mukeshsolanki/country-picker-android#52]
Hi,

Can you please give a parameterization for width to be configurable for country picker dialog view.

Please give an update on it.

**Comment by mukeshsolanki** [comment]
sure that makes sense will be included in the next release.

**Comment by vamsiandroid** [comment]
Okay,
Thanks.

**Comment by altaf2892** [comment]
yes match_parent is required
