### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [mukeshsolanki/country-picker-android#54]
Hello...

I came across your fantastic project and i wanted to help contribute to your project by using my Skills in Logo Design to contribute and help create a logo for your project...

I am already working on an idea... i will update what i have done here so you can give your feedback and possibly any change or tweek you may want...

you can also give your own idea...

Regards.

**Comment by chimzycash** [comment]
Hello...

Here is my idea design that i created... please do let me know if you want any tweak or color change....

You can share your own idea also...

if you like any of the design style... please do let me know and i will send you all the files and vector files for your use...

![logo design_country picker_different logo styles](https://user-images.githubusercontent.com/37814297/40274950-d0a8fa74-5bdb-11e8-92ca-288c52c7015d.jpg)


![logo design_country picker_different icon ideas](https://user-images.githubusercontent.com/37814297/40274951-d8596c4a-5bdb-11e8-98c8-2019e0777c83.jpg)

**Comment by chimzycash** [comment]
OK... VERY COOL... @mukeshsolanki

You can share with me if you got any other project you want me to contribute with my logo design and graphics skills...

**Comment by mukeshsolanki** [comment]
@chimzycash can u send me an email at mukesh@madapps.in and we can discuss further there.

**Comment by chimzycash** [comment]
@mukeshsolanki 

OK...
