### ISSUE TITLE
style colors

### ISSUE THREAD

**Issue by numez** [mukeshsolanki/country-picker-android#57]
I'm getting white text on white dialog background, how to style it?

![white](https://user-images.githubusercontent.com/6752432/40909284-784331c8-67e9-11e8-9bcb-20d6d5ff4d1f.png)

**Comment by mukeshsolanki** [comment]
The reason is most like because you have white color as the primary text color for your app in the `style.xml`.  the library does not support styling yet. This will be included in the next release.
