### ISSUE TITLE
county is not alphabetically ordered

### ISSUE THREAD

**Issue by WahdanZ** [mukeshsolanki/country-picker-android#67]
I try to use orderBy method but doesn't affect

**Comment by mukeshsolanki** [comment]
I'm not sure what you mean by using the orderBy method the library does not have an inbuilt method for orderBy.

**Comment by WahdanZ** [comment]
sorry for my mistake, I mean sortBy... I use it but the country is not sorted

**Comment by mukeshsolanki** [comment]
can you share your code? Also, which version of the library are you using?

**Comment by WahdanZ** [comment]
implementation 'com.github.mukeshsolanki:country-picker-android:1.2.5'

        countryPicker =
                new CountryPicker.Builder().with(getContext()).sortBy(1)
                        .listener(country -> {
                                    this.country = country;
                                    updateCountry(country.getDialCode(), country.getFlag());

                                }
                        )
                        .build();

**Comment by mukeshsolanki** [comment]
Instead of passing a `1` can you use `CountryPicker.SORT_BY`

**Comment by WahdanZ** [comment]
I used sortBy(CountryPicker.SORT_BY_NAME) and it's not working well  see the screenshot 

![image](https://user-images.githubusercontent.com/4412251/44949845-41330900-ae3a-11e8-8689-b3f11ae471ca.png)

**Comment by mukeshsolanki** [comment]
Can you try version `2.0.0`

**Comment by WahdanZ** [comment]
I try this version but it same result I think the code isn't updated
I pull the code on Github and compare it with the code on the library but it different 
you can check the diff here http://www.mergely.com/vvMSxUPa/

**Comment by mukeshsolanki** [comment]
it seems like a really weird issue that you are facing can you possible zip and example app with the issue and send it for us to further debug the issue?

**Comment by WahdanZ** [comment]
this link of example repo I wonder how the sort is working, i think in the private constructor the sortBy is sent with 0 ; this.sortBy = 0;
you can check the line 77  in class "CountryPicker"
also, there is some methods can't access 
getAllCountries()
https://github.com/WahdanZ/CcpExample

**Comment by WahdanZ** [comment]
any update?
