### ISSUE TITLE
Invalid default position on 21:9 screens

### ISSUE THREAD

**Issue by vanyasem** [mukeshsolanki/country-picker-android#71]
Version 2.0 opens above the status bar on Samsung Galaxy S8+ (21:9 aspect ratio):
![photo_2018-11-01_20-45-00](https://user-images.githubusercontent.com/13350458/47869106-1869c880-de17-11e8-97ff-1003a2cd688b.jpg)

After clicking on the Search Bar, it repositions correctly:
![photo_2018-11-01_20-45-42](https://user-images.githubusercontent.com/13350458/47869122-24558a80-de17-11e8-9b32-d24b646f27f8.jpg)
 itself:

**Comment by vanyasem** [comment]
Also worth mentioning that it has no padding around it, it clips to the screen

**Comment by vanyasem** [comment]
If you run the app in a "compatibility" mode (forcing 16:9), it starts in a correct location:
![photo_2018-11-01_20-49-17](https://user-images.githubusercontent.com/13350458/47869278-9cbc4b80-de17-11e8-8454-e0ae72a6967c.jpg)

**Comment by mukeshsolanki** [comment]
This seems to affect a small margin of devices and could take longer to fix. Please feel free to make a Pull Request

**Comment by mukeshsolanki** [comment]
@vanyasem can you check if the latest version (2.0.1) still has this issue?
