### ISSUE TITLE
Bottom sheet - one country behind the keyboard

### ISSUE THREAD

**Issue by vanyasem** [mukeshsolanki/country-picker-android#72]
One country behind the keyboard. Tested with Gboard and Samsung Keyboard. This is very annoying if you only have one result on screen, as it covers the only result 

![2018-11-02-001901_531x376_scrot](https://user-images.githubusercontent.com/13350458/47880685-ed8e6d00-de34-11e8-99b6-694bbb5b99b5.png)
![2018-11-02-001905_522x265_scrot](https://user-images.githubusercontent.com/13350458/47880686-ed8e6d00-de34-11e8-9b0e-57f34275190b.png)

**Comment by vanyasem** [comment]
Or maybe this https://stackoverflow.com/questions/42944750/android-bottomsheetdialog-with-edittext-covered-by-keyboard

**Comment by mukeshsolanki** [comment]
Thanks for reporting this @vanyasem i will be fixing this in the upcoming release which should be this weekend :)
