### ISSUE TITLE
Error in latest version

### ISSUE THREAD

**Issue by AstonBraham** [mukeshsolanki/country-picker-android#76]
Hello,
Thanks for your breat Work

I followed all the steps but I'm getting this error

java.lang.NoSuchFieldError: No field country_flag of type I in class Lcom/mukesh/countrypicker/R$id; or its superclasses (declaration of 'com.mukesh.countrypicker.R$id' appears in /data/app/com.package.app/base.apk)

How can I fix this please ?

**Comment by mukeshsolanki** [comment]
This looks like an issue with dex and not with the library can you check if your project uses dex properly and you have pro-guard properly set up. Also, can you share a snippet of how you are producing this issue?

**Comment by AstonBraham** [comment]
Finally got if fidex.. I imported your code as module into my project, and refactored android deprendencies to androidx.
Thanks Sir @mukeshsolanki for such a great library.
