### ISSUE TITLE
Keyboard not closing.

### ISSUE THREAD

**Issue by nareshkatta99** [mukeshsolanki/country-picker-android#78]
After opening the dialog,
When I select search and input some data into search,
Keyboard not closing after selecting the country.

### Steps to reproduce
Enter data into search and directly select country

### Expected behaviour
Keyboard needs to be closed

### Actual behaviour
Keyboard not closing

#### More details:
Android version: 5.1
Mobile: Oppo

**Comment by mukeshsolanki** [comment]
can you share a bit of the code?

**Comment by mshaq09** [comment]
This is still happening 

Steps to reproduce
Enter data into search and directly select country

Expected behaviour
Keyboard needs to be closed

Actual behaviour
Keyboard not closing
