### ISSUE TITLE
Keyboard doesn't close on back screen if country selected after searching from dialog fragment (fine in bottom sheet)

### ISSUE THREAD

**Issue by surbhi-jungleworks** [mukeshsolanki/country-picker-android#90]
### Subject of the issue
Describe your issue here.

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by gauravsoni020** [comment]
Just Use the below code to hide the keyboard inside listner 

               ` CountryPicker.Builder builder = new CountryPicker.Builder().with(this)
                        .listener(new OnCountryPickerListener() {
                            @Override
                            public void onSelectCountry(Country country) {
                                countryCodeTv.setText(country.getDialCode());
                                getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN);
                            }
                        });

`

**Comment by surbhi-jungleworks** [comment]
Yes, that i have already handled at my end because it's already too late
