### ISSUE TITLE
To change device locale Index out of bound exception.

### ISSUE THREAD

**Issue by Anujimark** [mukeshsolanki/country-picker-android#92]
java.lang.StringIndexOutOfBoundsException: length=0; index=2

 public Country getCountryByLocale(@NonNull Locale locale) {  // **set locale "ar"**
        String countryIsoCode = locale.getISO3Country().substring(0, 2).toLowerCase(); // **"locale.getISO3Country()" not found the result return "" string. thats way substring array not matches.**
        return getCountryByISO(countryIsoCode);
    }

**Comment by lfongaroScp** [comment]
Try with 
`locale.getCountry()`

the two letter ISO is not always the 3 letter except the last. Sweden, for example. Three letter: SWE. Two letter: SE

**Comment by mukeshsolanki** [comment]
Fixed in the latest version
