### ISSUE TITLE
Need to translate the "Search" text

### ISSUE THREAD

**Issue by Sahilpuri007** [mukeshsolanki/country-picker-android#95]
### Subject of the issue
Using this is an all-French text app. But unable to change "Search" in the dialog in french

### Steps to reproduce
Open the dialog. Search view text

### Expected behaviour
Should be able to provide and set this string according to app language

### Actual behaviour
Always in English

**Comment by Tavorcl** [comment]
+1. I also need this. There isn't a way to do it?

**Comment by Sahilpuri007** [comment]
why ? can you explain
