### ISSUE TITLE
Myanmar Country Flag is incorrect

### ISSUE THREAD

**Issue by waqarkhan327** [mukeshsolanki/country-picker-android#99]
### Subject of the issue
Myanmar Country Flag is incorrect. Please check

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by mukeshsolanki** [comment]
Thanks for reporting the issue has been resolved in the newer version releasing today.
